name: Testing

on:
  workflow_dispatch:

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Curl with Indian Proxy
        run: |
          curl -x http://195.250.31.18:80 \
            -H "User-Agent: Mozilla/5.0" \
            --max-time 30 \
            -v \
            "https://mnregaweb4.nic.in/nregaarch/View_NMMS_atten_date_new.aspx?page=D&short_name=UP&state_name=UTTAR%20PRADESH&state_code=31&district_name=BASTI&district_code=3153&fin_year=2024-2025&AttendanceDate=31/03/2025&source=&Digest=ebKjCj4U7oFg7NTclfvy5A"
